/**
 * Generated with the enum generator.
 * Please DO NOT modify this directly.
 * If it's needed to update, Modify bdsx-lib/minecraft/enums_ini/*.ini instead
 */
declare module "." {
    enum AbilitiesIndex {
        Build,
        Mine,
        DoorsAndSwitches,
        OpenContainers,
        AttackPlayers,
        AttackMobs,
        OperatorCommands,
        Teleport,
        // Both are 8
        ExposedAbilityCount,
        Invulnerable = 8,
        Flying,
        MayFly,
        Instabuild,
        Lightning,
        FlySpeed,
        WalkSpeed,
        Muted,
        WorldBuilder,
        NoClip,
        AbilityCount,
    }
    namespace Ability {
        enum Options {
            None,
            NoSave,
            CommandExposed = 2,
            PermissionsInterfaceExposed = 4,
            WorldbuilderOverrides = 8,
            NoSaveCommandExposed = 3,
            NoSavePermissionsInterfaceExposed = 5,
            CommandExposedPermissionsInterfaceExposed = 6,
            NoSaveCommandExposedPermissionsInterfaceExposed = 7,
            NoSaveWorldbuilderOverrides = 9,
            CommandExposedWorldbuilderOverrides = 10,
            NoSaveCommandExposedWorldbuilderOverrides = 11,
            PermissionsInterfaceExposedWorldbuilderOverrides = 12,
            NoSavePermissionsInterfaceExposedWorldbuilderOverrides = 13,
            CommandExposedPermissionsInterfaceExposedWorldbuilderOverrides = 14,
            All = 15,
        }
    }
    namespace Ability {
        enum Type {
            Invalid,
            Unset,
            Bool,
            Float,
        }
    }
    enum ActorDamageCause {
        /** The kill command */
        Override,
        /** @deprecated */
        None = 0,
        Contact,
        EntityAttack,
        Projectile,
        Suffocation,
        /** @deprecated Typo */
        Suffoocation = 4,
        Fall,
        Fire,
        FireTick,
        Lava,
        Drowning,
        BlockExplosion,
        EntityExplosion,
        Void,
        Suicide,
        Magic,
        Wither,
        Starve,
        Anvil,
        Thorns,
        FallingBlock,
        Piston,
        FlyIntoWall,
        Magma,
        Fireworks,
        Lightning,
        Charging,
        Temperature = 0x1A,
        All = 0x1F,
    }
    namespace ActorEventPacket {
        enum Events {
            Jump = 1,
            HurtAnimation,
            DeathAnimation,
            ArmSwing,
            StopAttack,
            TameFail,
            TameSuccess,
            ShakeWet,
            UseItem,
            EatGrassAnimation,
            FishHookBubble,
            FishHookPosition,
            FishHookHook,
            FishHookTease,
            SquidInkCloud,
            ZombieVillagerCure,
            AmbientSound,
            Respawn,
            IronGolemOfferFlower,
            IronGolemWithdrawFlower,
            LoveParticles,
            VillagerAngry,
            VillagerHappy,
            WitchSpellParticles,
            FireworkParticles,
            InLoveParticles,
            SilverfishSpawnAnimation,
            GuardianAttack,
            WitchDrinkPotion,
            WitchThrowPotion,
            MinecartTntPrimeFuse,
            CreeperPrimeFuse,
            AirSupplyExpired,
            PlayerAddXpLevels,
            ElderGuardianCurse,
            AgentArmSwing,
            EnderDragonDeath,
            DustParticles,
            ArrowShake,
            EatingItem = 57,
            BabyAnimalFeed = 60,
            DeathSmokeCloud,
            CompleteTrade,
            RemoveLeash,
            ConsumeTotem = 65,
            PlayerCheckTreasureHunterAchievement,
            EntitySpawn,
            DragonPuke,
            ItemEntityMerge,
            StartSwim,
            BalloonPop,
            TreasureHunt,
            AgentSummon,
            ChargedCrossbow,
            Fall,
        }
    }
    enum ActorFlags {
        OnFire,
        Sneaking,
        Riding,
        Sprinting,
        UsingItem,
        Invisible,
        Tempted,
        InLove,
        Saddled,
        Powered,
        Ignit0ed,
        Baby,
        Converting,
        Critical,
        CanShowName,
        AlwaysShowName,
        NoAI,
        Silent,
        WallClimbing,
        CanClimb,
        CanSwim,
        CanFly,
        CanWalk,
        Resting,
        Sitting,
        Angry,
        Interested,
        Charged,
        Tamed,
        Orphaned,
        Leashed,
        Sheared,
        Gliding,
        Elder,
        Moving,
        Breathing,
        Chested,
        Stackable,
        ShowBottom,
        Standing,
        Shaking,
        Idling,
        Casting,
        Charging,
        WasdControlled,
        CanPowerJump,
        Lingering,
        HasCollision,
        HasGravity,
        FireImmune,
        Dancing,
        Enchanted,
        ReturnTrident,
        ContainerIsPrivate,
        IsTransforming,
        DamageNearbyMobs,
        Swimming,
        Bribed,
        IsPregnant,
        LayingEgg,
        RiderCanPick,
        TransitionSitting,
        Eating,
        LayingDown,
        Snezing,
        Trusting,
        Rolling,
        Scared,
        InScaffolding,
        OverScaffolding,
        FallThroughScaffolding,
        Blocking,
        TransitionBlocking,
        BlockedUsingShield,
        BlockedUsingDamagedShield,
        Sleeping,
        WantsToWake,
        TradeInterest,
        DoorBreaker,
        BreakingObstruction,
        DoorOpener,
        IsIllagerCaptain,
        Stunned,
        Roaring,
        DelayedAttack,
        IsAvoidingMobs,
        FacingTargetToRangeAttack,
        HiddenWhenInvisible,
        IsInUI,
        Stalking,
        Emoting,
        Celebrating,
    }
    enum ActorType {
        Item = 0x40,
        PrimedTnt,
        FallingBlock,
        MovingBlock,
        Experience,
        EyeOfEnder,
        EnderCrystal,
        FireworksRocket,
        FishingHook = 0x4D,
        Chalkboard,
        Painting = 0x53,
        LeashKnot = 0x58,
        BoatRideable = 0x5A,
        LightningBolt = 0x5D,
        AreaEffectCloud,
        Balloon = 0x6B,
        Shield = 0x75,
        Lectern = 0x77,
        TypeMask = 0xFF,
        Mob,
        Npc = 0x133,
        Agent = 0x138,
        ArmorStand = 0x13D,
        TripodCamera,
        Player,
        Bee = 0x17A,
        Piglin,
        PiglinBrute = 0x17F,
        PathfinderMob = 0x300,
        IronGolem = 0x314,
        SnowGolem,
        WanderingTrader = 0x376,
        Monster = 0xB00,
        Creeper = 0xB21,
        Slime = 0xB25,
        EnderMan,
        Ghast = 0xB29,
        LavaSlime = 0xB2A,
        Blaze,
        Witch = 0xB2D,
        Guardian = 0xB31,
        ElderGuardian,
        Dragon = 0xB35,
        Shulker,
        Vindicator = 0xB39,
        IllagerBeast = 0xB3B,
        EvocationIllager = 0xB68,
        Vex,
        Pillager = 0xB72,
        ElderGuardianGhost = 0xB78,
        Animal = 0x1300,
        Chicken = 0x130A,
        Cow,
        Pig,
        Sheep,
        MushroomCow = 0x1310,
        Rabbit = 0x1312,
        PolarBear = 0x131C,
        Llama,
        Turtle = 0x134A,
        Panda = 0x1371,
        Fox = 0x1379,
        Hoglin = 0x137C,
        Strider,
        Goat = 0x1380,
        Axolotl = 0x1382,
        WaterAnimal = 0x2300,
        Squid = 0x2311,
        Dolphin = 0x231F,
        Pufferfish = 0x236C,
        Salmon,
        Tropicalfish = 0x236F,
        Fish,
        GlowSquid = 0x2381,
        TameableAnimal = 0x5300,
        Wolf = 0x530E,
        Ocelot = 0x5316,
        Parrot = 0x531E,
        Cat = 0x534B,
        Ambient = 0x8100,
        Bat = 0x8113,
        UndeadMob = 0x10B00,
        PigZombie = 0x10B24,
        WitherBoss = 0x10B34,
        Phantom = 0x10B3A,
        Zoglin = 0x10B7E,
        ZombieMonster = 0x30B00,
        Zombie = 0x30B20,
        ZombieVillager = 0x30B2C,
        Husk = 0x30B2F,
        Drowned = 0x30B6E,
        ZombieVillagerV2 = 0x30B74,
        Arthropod = 0x40B00,
        Spider = 0x40B23,
        Silverfish = 0x40B27,
        CaveSpider,
        Endermite = 0x40B37,
        Minecart = 0x80000,
        MinecartRideable = 0x80054,
        MinecartHopper = 0x80060,
        MinecartTNT,
        MinecartChest,
        MinecartFurnace,
        MinecartCommandBlock,
        SkeletonMonster = 0x110B00,
        Skeleton = 0x110B22,
        Stray = 0x110B2E,
        WitherSkeleton = 0x110B30,
        EquineAnimal = 0x205300,
        Horse = 0x205317,
        Donkey,
        Mule,
        SkeletonHorse = 0x215B1A,
        ZombieHorse,
        Projectile = 0x400000,
        ExperiencePotion = 0x400044,
        ShulkerBullet = 0x40004C,
        DragonFireball = 0x40004F,
        Snowball = 0x400051,
        ThrownEgg,
        LargeFireball = 0x400055,
        ThrownPotion,
        Enderpearl,
        WitherSkull = 0x400059,
        WitherSkullDangerous = 0x40005B,
        SmallFireball = 0x40005E,
        LingeringPotion = 0x400065,
        LlamaSpit,
        EvocationFang,
        IceBomb = 0x40006A,
        AbstractArrow = 0x800000,
        Trident = 0x0C00049,
        Arrow,
        VillagerBase = 0x1000300,
        Villager = 0x100030F,
        VillagerV2 = 0x1000373,
    }
    namespace AnimatePacket {
        enum Actions {
            SwingArm = 1,
            WakeUp = 3,
            CriticalHit,
            MagicCriticalHit,
            RowRight = 128,
            RowLeft,
        }
    }
    enum ArmorSlot {
        Head,
        /** IDA said this is called Torso */
        Torso,
        Chest = 1,
        Legs,
        Feet,
    }
    namespace BookEditPacket {
        enum Types {
            ReplacePage,
            AddPage,
            DeletePage,
            SwapPages,
            SignBook,
        }
    }
    namespace BossEventPacket {
        enum Colors {
            Pink,
            Blue,
            Red,
            Green,
            Yellow,
            Purple,
            White,
        }
    }
    namespace BossEventPacket {
        enum Overlay {
            Progress,
            Notched6,
            Notched10,
            Notched12,
            Notched20,
        }
    }
    namespace BossEventPacket {
        enum Types {
            Show,
            RegisterPlayer,
            Hide,
            UnregisterPlayer,
            HealthPercent,
            Title,
            Properties,
            Style,
        }
    }
    enum BuildPlatform {
        /** https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/network/mcpe/protocol/types/DeviceOS.php */
        UNKNOWN=-1,
        ANDROID = 1,
        IOS = 2,
        OSX = 3,
        AMAZON = 4,
        GEAR_VR = 5,
        HOLOLENS = 6,
        WINDOWS_10 = 7,
        WIN32 = 8,
        DEDICATED = 9,
        TVOS = 10,
        PLAYSTATION = 11,
        NINTENDO = 12,
        XBOX = 13,
        WINDOWS_PHONE = 14,
    }
    namespace CameraShakePacket {
        enum ShakeAction {
            Add,
            Stop,
        }
    }
    namespace CameraShakePacket {
        enum ShakeType {
            Positional,
            Rotational,
        }
    }
    enum CommandParameterDataType {
        NORMAL,
        ENUM,
        SOFT_ENUM,
        POSTFIX,
    }
    enum CommandPermissionLevel {
        Normal,
        Operator,
        Host,
        Automation,
        Admin,
        Internal,
    }
    namespace CompletedUsingItemPacket {
        enum Actions {
            EquipArmor,
            Eat,
            Attack,
            Consume,
            Throw,
            Shoot,
            Place,
            FillBottle,
            FillBucket,
            PourBucket,
            UseTool,
            Interact,
            Retrieved,
            Dyed,
            Traded,
        }
    }
    namespace ComplexInventoryTransaction {
        enum Type {
            NormalTransaction,
            InventoryMismatch,
            ItemUseTransaction,
            ItemUseOnEntityTransaction,
            ItemReleaseTransaction,
        }
    }
    enum ContainerType {
        Container,
        Workbench,
        Furnace,
        Enchantment,
        BrewingStand,
        Anvil,
        Dispenser,
        Dropper,
        Hopper,
        Cauldron,
        MinecartChest,
        MinecartHopper,
        Horse,
        Beacon,
        StructureEditor,
        Trade,
        CommandBlock,
        Jukebox,
        Armor,
        Hand,
        CompoundCreator,
        ElementConstructor,
        MaterialReducer,
        LabTable,
        Loom,
        Lectern,
        Grindstone,
        BlastFurnace,
        Smoker,
        Stonecutter,
        Cartography,
        None = 0xF7,
        Inventory = 0xFF,
    }
    enum CreativeItemCategory {
        All,
        Construction,
        Nature,
        Equipment,
        Items,
        Uncategorized,
    }
    enum Difficulty {
        Peaceful,
        Easy,
        Normal,
        Hard,
    }
    enum DimensionId {
        Overworld = 0,
        Nether = 1,
        TheEnd = 2,
    }
    namespace Enchant {
        enum Type {
            ArmorAll,
            ArmorFire,
            ArmorFall,
            ArmorExplosive,
            ArmorProjectile,
            ArmorThorns,
            WaterBreath,
            WaterSpeed,
            WaterAffinity,
            WeaponDamage,
            WeaponUndead,
            WeaponArthropod,
            WeaponKnockback,
            WeaponFire,
            WeaponLoot,
            MiningEfficiency,
            MiningSilkTouch,
            MiningDurability,
            MiningLoot,
            BowDamage,
            BowKnockback,
            BowFire,
            BowInfinity,
            FishingLoot,
            FishingLure,
            FrostWalker,
            Mending,
            CurseBinding,
            CurseVanishing,
            TridentImpaling,
            TridentRiptide,
            TridentLoyalty,
            TridentChanneling,
            CrossbowMultishot,
            CrossbowPiercing,
            CrossbowQuickCharge,
            SoulSpeed,
            NumEnchantments,
            InvalidEnchantment,
            // Alternative names
            Protection = 0,
            FireProtection = 1,
            FeatherFalling = 2,
            BlastProtection = 3,
            ProjectileProtection = 4,
            Thorns = 5,
            Respiration = 6,
            DepthStrider = 7,
            AquaAffinity = 8,
            Sharpness = 9,
            Smite = 10,
            BaneOfArthropods = 11,
            Knockback = 12,
            FireAspect = 13,
            Looting = 14,
            Efficiency = 15,
            SilkTouch = 16,
            Unbreaking = 17,
            Fortune = 18,
            Power = 19,
            Punch = 20,
            Flame = 21,
            Infinity = 22,
            LuckOfTheSea = 23,
            Lure = 24,
            // FrostWalker = 25
            // Mending = 26
            BindingCurse = 27,
            VanishingCurse = 28,
            Impaling = 29,
            Riptide = 30,
            Loyalty = 31,
            Channeling = 32,
            Multishot = 33,
            Piercing = 34,
            QuickCharge = 35,
            // SoulSpeed = 36
        }
    }
    namespace Facing {
        enum Name {
            Down,
            Up,
            North,
            South,
            West,
            East,
            Max,
        }
    }
    namespace GameRule {
        enum Type {
            Invalid,
            Bool,
            Int,
            Float,
        }
    }
    enum GameType {
        Survival,
        Creative,
        Adventure,
        SurvivalSpectator,
        CreativeSpectator,
        Default,
    }
    namespace IdentityDefinition {
        enum Type {
            Invalid,
            Player,
            Entity,
            FakePlayer,
        }
    }
    namespace InteractPacket {
        enum Actions {
            LeaveVehicle = 3,
            Mouseover,
            OpenNPC,
            OpenInventory,
        }
    }
    namespace ItemReleaseInventoryTransaction {
        enum ActionType {
            Release,
            Use,
        }
    }
    namespace ItemUseInventoryTransaction {
        enum ActionType {
            Place,
            Use,
            Destroy,
        }
    }
    namespace ItemUseOnActorInventoryTransaction {
        enum ActionType {
            Interact,
            Attack,
            ItemInteract,
        }
    }
    namespace Json {
        enum ValueType {
            Null = 0,
            Int32 = 1,
            Int64 = 2,
            Float64 = 3,
            String = 4,
            Boolean = 5,
            Array = 6,
            Object = 7,
        }
    }
    enum MinecraftPacketIds {
        Login = 1,
        PlayStatus = 2,
        ServerToClientHandshake = 3,
        ClientToServerHandshake = 4,
        Disconnect = 5,
        ResourcePacksInfo = 6,
        ResourcePackStack = 7,
        ResourcePackClientResponse = 8,
        Text = 9,
        SetTime = 10,
        StartGame = 11,
        AddPlayer = 12,
        AddActor = 13,
        RemoveActor = 14,
        AddItemActor = 15,
        TakeItemActor = 17,
        MoveActorAbsolute = 18,
        MovePlayer = 19,
        RiderJump = 20,
        UpdateBlock = 21,
        AddPainting = 22,
        TickSync = 23,
        LevelSoundEventV1 = 24,
        LevelEvent = 25,
        BlockEvent = 26,
        ActorEvent = 27,
        MobEffect = 28,
        UpdateAttributes = 29,
        InventoryTransaction = 30,
        MobEquipment = 31,
        MobArmorEquipment = 32,
        Interact = 33,
        BlockPickRequest = 34,
        ActorPickRequest = 35,
        PlayerAction = 36,
        HurtArmor = 38,
        SetActorData = 39,
        SetActorMotion = 40,
        SetActorLink = 41,
        SetHealth = 42,
        SetSpawnPosition = 43,
        Animate = 44,
        Respawn = 45,
        ContainerOpen = 46,
        ContainerClose = 47,
        PlayerHotbar = 48,
        InventoryContent = 49,
        InventorySlot = 50,
        ContainerSetData = 51,
        CraftingData = 52,
        CraftingEvent = 53,
        GuiDataPickItem = 54,
        AdventureSettings = 55,
        BlockActorData = 56,
        PlayerInput = 57,
        LevelChunk = 58,
        SetCommandsEnabled = 59,
        SetDifficulty = 60,
        ChangeDimension = 61,
        SetPlayerGameType = 62,
        PlayerList = 63,
        SimpleEvent = 64,
        Event = 65,
        SpawnExperienceOrb = 66,
        ClientboundMapItemData = 67,
        MapInfoRequest = 68,
        RequestChunkRadius = 69,
        ChunkRadiusUpdated = 70,
        ItemFrameDropItem = 71,
        GameRulesChanged = 72,
        Camera = 73,
        BossEvent = 74,
        ShowCredits = 75,
        AvailableCommands = 76,
        CommandRequest = 77,
        CommandBlockUpdate = 78,
        CommandOutput = 79,
        UpdateTrade = 80,
        UpdateEquip = 81,
        ResourcePackDataInfo = 82,
        ResourcePackChunkData = 83,
        ResourcePackChunkRequest = 84,
        Transfer = 85,
        PlaySound = 86,
        StopSound = 87,
        SetTitle = 88,
        AddBehaviorTree = 89,
        StructureBlockUpdate = 90,
        ShowStoreOffer = 91,
        PurchaseReceipt = 92,
        PlayerSkin = 93,
        SubClientLogin = 94,
        AutomationClientConnect = 95,
        SetLastHurtBy = 96,
        BookEdit = 97,
        NpcRequest = 98,
        PhotoTransfer = 99,
        ModalFormRequest = 100,
        ModalFormResponse = 101,
        ServerSettingsRequest = 102,
        ServerSettingsResponse = 103,
        ShowProfile = 104,
        SetDefaultGameType = 105,
        RemoveObjective = 106,
        SetDisplayObjective = 107,
        SetScore = 108,
        LabTable = 109,
        UpdateBlockSynced = 110,
        MoveActorDelta = 111,
        SetScoreboardIdentity = 112,
        SetLocalPlayerAsInitialized = 113,
        UpdateSoftEnum = 114,
        NetworkStackLatency = 115,
        ScriptCustomEvent = 117,
        SpawnParticleEffect = 118,
        AvailableActorIdentifiers = 119,
        LevelSoundEventV2 = 120,
        NetworkChunkPublisherUpdate = 121,
        BiomeDefinitionList = 122,
        LevelSoundEvent = 123,
        LevelEventGeneric = 124,
        LecternUpdate = 125,
        AddEntity = 127,
        RemoveEntity = 128,
        ClientCacheStatus = 129,
        OnScreenTextureAnimation = 130,
        MapCreateLockedCopy = 131,
        StructureTemplateDataRequest = 132,
        StructureTemplateDataResponse = 133,
        ClientCacheBlobStatus = 135,
        ClientCacheMissResponse = 136,
        EducationSettings = 137,
        Emote = 138,
        MultiplayerSettings = 139,
        SettingsCommand = 140,
        AnvilDamage = 141,
        CompletedUsingItem = 142,
        NetworkSettings = 143,
        PlayerAuthInput = 144,
        CreativeContent = 145,
        PlayerEnchantOptions = 146,
        ItemStackRequest = 147,
        ItemStackResponse = 148,
        PlayerArmorDamage = 149,
        CodeBuilder = 150,
        UpdatePlayerGameType = 151,
        EmoteList = 152,
        PositionTrackingDBServerBroadcast = 153,
        PositionTrackingDBClientRequest = 154,
        DebugInfo = 155,
        PacketViolationWarning = 156,
        MotionPredictionHints = 157,
        AnimateEntity = 158,
        CameraShake = 159,
        PlayerFog = 160,
        CorrectPlayerMovePrediction = 161,
        ItemComponent = 162,
        FilterText = 163,
        ClientboundDebugRenderer = 164,
        SyncActorProperty = 165,
        AddVolumeEntity = 166,
        RemoveVolumeEntity = 167,
        SimulationType = 168,
        NpcDialogue = 169,
    }
    namespace MovePlayerPacket {
        enum Modes {
            Normal,
            Reset,
            Teleport,
            Pitch,
        }
    }
    namespace NpcDialoguePacket {
        enum Actions {
            Open,
            Close,
        }
    }
    enum ObjectiveSortOrder {
        Ascending,
        Descending,
    }
    enum PackType {
        Invalid,
        Addon,
        Cached,
        CopyProtected,
        Behavior,
        PersonaPiece,
        Resources,
        Skins,
        WorldTemplate,
        Count,
    }
    namespace PlayerActionPacket {
        enum Actions {
            /** @deprecated */
            StartBreak,
            /** @deprecated */
            AbortBreak,
            /** @deprecated */
            StopBreak,
            GetUpdatedBlock,
            /** @deprecated */
            DropItem,
            StartSleeping,
            StopSleeping,
            Respawn,
            /** @deprecated */
            Jump,
            /** @deprecated */
            StartSprint,
            /** @deprecated */
            StopSprint,
            /** @deprecated */
            StartSneak,
            /** @deprecated */
            StopSneak,
            CreativePlayerDestroyBlock,
            DimensionChangeAck,
            /** @deprecated */
            StartGlide,
            /** @deprecated */
            StopGlide,
            /** @deprecated */
            BuildDenied,
            CrackBreak,
            /** @deprecated */
            ChangeSkin,
            /** @deprecated */
            SetEnchantmentSeed,
            /** @deprecated */
            StartSwimming,
            /** @deprecated */
            StopSwimming,
            StartSpinAttack,
            StopSpinAttack,
            InteractBlock,
            PredictDestroyBlock,
            ContinueDestroyBlock,
        }
    }
    enum PlayerScoreSetFunction {
        Set,
        Add,
        Subtract,
    }
    namespace PositionTrackingDBClientRequestPacket {
        enum Actions {
            Query,
        }
    }
    namespace PositionTrackingDBServerBroadcastPacket {
        enum Actions {
            Update,
            Destroy,
            NotFound,
        }
    }
    enum ResourcePackResponse {
        Cancel = 1,
        Downloading,
        DownloadingFinished,
        ResourcePackStackFinished,
    }
    namespace ScorePacketInfo {
        enum Type {
            PLAYER = 1,
            ENTITY = 2,
            FAKE_PLAYER = 3,
        }
    }
    namespace SetScorePacket {
        enum Type {
            CHANGE = 0,
            REMOVE = 1,
        }
    }
    namespace SetTitlePacket {
        enum Types {
            Clear,
            Reset,
            Title,
            Subtitle,
            Actionbar,
            AnimationTimes,
        }
    }
    enum StreamReadResult {
        NoError = 0,
        Error = 1,
        /** disconnect at 3 times */
        Warning = 2,
        /** Custom code by BDSX */
        Ignore = 0x7f,
    }
    namespace TextPacket {
        enum Types {
            Raw,
            Chat,
            Translate,
            /** @deprecated */
            Translated = 2,
            Popup,
            JukeboxPopup,
            Tip,
            SystemMessage,
            /** @deprecated */
            Sytem = 6,
            Whisper,
            /** /say command */
            Announcement,
            TextObject,
            /** @deprecated */
            ObjectWhisper = 9,
        }
    }
    namespace UpdateBlockPacket {
        enum DataLayerIds {
            Normal,
            Liquid,
        }
    }
    namespace UpdateBlockPacket {
        enum Flags {
            None,
            Neighbors,
            Network,
            All,
            NoGraphic,
            Priority = 8,
            AllPriority = 11,
        }
    }
}
export {};
