name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BDSX_YES: skip

    steps:
      - uses: actions/checkout@v2

      - name: NPM Install 
        run: npm i
        working-directory: bdsx-lib

      - name: TypeScript Check
        run: tsc --noEmit
        working-directory: bdsx-lib
        
      - name: ESLint
        run: npm run lint-bdsx
        working-directory: bdsx-lib
